### ISSUE TITLE
Issue running ds_illum

### ISSUE THREAD

**Issue by twanito** [MITSustainableDesignLab/Daysim#2]
Hi,

I have been having some issues with running ds_illum command on windows. I think it has something to do with the way I am naming my files. The error I get is that ds_illum just crashes.

I have dumped the files [here](https://github.com/twanito/ds_illum_bug), the top folder works and the one underneath does not. I have made parametric run of 800 odd options and only the folders ending in "HorizontalShade_0" seem to work. Any clues as to what might be causing this issue?

Cheers,

Antoine

**Comment by nljones** [comment]
The issue is fixed in the [latest commit](https://github.com/MITSustainableDesignLab/Daysim/commit/50f92015ac363db1685b0eb4b20920ef48f67208).
