### ISSUE TITLE
rtrace_dc

### ISSUE THREAD

**Issue by MarcoManzan** [MITSustainableDesignLab/Daysim#3]
I am trying to compile Daysim on windows, I followed the instructions and the project compiles without errors. However, when I run rtrace under bin/Debug it doesn't understands option -L introduced in Daysim, so I suspect I'm running a RADIANCE version. I tried to compile with option -DDAYSIM but in this case I obtain a number of errors about unsatisfied symbols. 
Have I to complete some additional configuration?
Thankyou 
Marco

**Comment by nljones** [comment]
Can you post the errors you receive? The -DDAYSIM flag is only to be used for compiling rtrace to make the Daysim version rtrace_dc. The flag will not work with the other Radiance programs presently.

**Comment by MarcoManzan** [comment]
dear nljones, I solved the problem by adding daysim.c to the lists  "add_library(radiance" in src\rt\CMakelists,txt. The errors were issued during link time by the lack of the routines defined in daysim.c

Thanks
Marco
