### ISSUE TITLE
install files

### ISSUE THREAD

**Issue by MarcoManzan** [MITSustainableDesignLab/Daysim#4]
I'm sorry, I inadvertently closed my previous issue. I solved the link problems by adding “daysim.c” to src/rt/CmaleLists.txt it appeared the file was not compiled at all, so the references to routines were missing and errors at link time issued. 
I have an additional question to formulate, how I install the programs in the desired location, in my case “Program Files”/DAYSIM ? Is there the corresponding action of a Linux “make install”?
Thanks

**Comment by nljones** [comment]
There is no installer package for Daysim executables that you compile yourself. You can specify a directory for binaries using CMake or Visual Studio, or you can drag the files to the desired location after you compile them. You can also add that location to your system or user path environment variable manually.
