### ISSUE TITLE
how to compile rtrace_dc_2305?

### ISSUE THREAD

**Issue by philipjss** [MITSustainableDesignLab/Daysim#6]
Hello,

I am looking for information on how to compile rtrace_dc_2305.

I am running Daysim's gen_dc program with the -dds option and it is falling over because it cannot find rtrace_dc_2305. See https://github.com/MITSustainableDesignLab/Daysim/blob/master/src/daysim/gen_dc.c#L625

This project's README file says "Programs maintained here that require manual intervention to compile (in src/rt): rtrace_dc, rtrace_dc_2305"

* Where is the source code for rtrace_dc_2305? I cannot find it in https://github.com/MITSustainableDesignLab/Daysim/tree/master/src/rt
* How can I build rtrace_dc_2305? 
* What sort of manual intervention is required to build it?
* could it be that rtrace_dc_2305 is to be created manually by modifying rtrace_dc?

I need to build rtrace_dc_2305 for Linux, is that possible? The README says  'Programs in this repository compile on Windows (VS2013) and Mac (XCode)'. Is it possible to compile them on Linux?

I have a slightly modified copy of Daysim 4.0 which allows building for Linux, and when I build it, it produces an executable for rtrace_dc, but not one for rtrace_dc_2305 (just like your version, it does not contain source code for rtrace_dc_2305).

Any information you may have that could help me figure out how to provide rtrace_dc_2305 to gen_dc (on Linux), will be greatly appreciated.

Thank you in advance for your help,

Philip Schwarz

P.S. to be more precise, when I say that gen_dc cannot find rtrace_dc_2305 I mean that gen_dc generates a file called static_system.dir-dir.ab0.dc cotaining the following command referencing rtrace_dc_2305:

```
# RADIANCE 4.1a; with Photon Map Extension 4.3.1, Daysim Extension
# /usr/local/bin/daysim-radiance/rtrace_dc_2305  -h -I+ -oc -aa 0.150000 -ab 0 -ad 256 -ar 32 -as 20 -dj 0.700000 -dr 0 -ds 0.000000 
```

When the command gets executed the following error occurs: sh: 1: /usr/local/bin/daysim-radiance/rtrace_dc_2305: not found

**Comment by nljones** [comment]
My best guess is that you need to edit daysim.c to use `daysimComputePatchDDS` in place of `daysimComputePatch` and then compile the code with the -DDAYSIM flag as described in #1 and #3.

Good luck if you decide to try this!

**Comment by philipjss** [comment]
Hello @nljones  

thank you very much for getting back to me.

> edit daysim.c to use daysimComputePatchDDS in place of daysimComputePatch

daysim.c doesn't use daysimComputePatchDDS, it provides it. source.c uses (calls) daysimComputePatch. So you must mean either edit source.c to call daysimComputePatchDDS rather than daysimComputePatch, or edit daysim.c and rename daysimComputePatch to say daysimComputePatchUnused and rename daysimComputePatchDDS to daysimComputePatch.

Either way, how can a change to the logic provided by daysim.c result in the source code for rtrace_dc_2305 being generated and compiled?

![image](https://user-images.githubusercontent.com/24895920/41406423-41a87820-6fc4-11e8-9c15-53997c91ed55.png)

The problem I have is that gen_dc needs to call an executable called rtrace_dc_2305 but I do not have that executable and I don't know why it doesn't exist, or how it can be created, and using which source code.

Maybe you meant that having made those changes, and done a build, the resulting rtrace_dc can be renamed to rtrace_dc_2305. I did have a go at that, I took just rtrace_dc_2305, and dropped it next to rtrace_dc in the bin directory I am currently using, and then I ran gen_dc proj.hea -dds again, and the resulting error changed as follows (before --> after):

![image](https://user-images.githubusercontent.com/24895920/41407212-a4610476-6fc6-11e8-9d61-238f4b37db8b.png)

What I find frustrating is that I have someone with a requirement to run gen_dc with the -dds option and they can just install daysim on windows and they can see rtrace_dc_2305.exe among the installed file, and calling gen_dc with -dds works for them, but I then have to implement this on Linux and for some reason there is no clear documentation saying that generation of a rtrace_dc_2305 binary is optional and explaining how to build it.

Do you have any further thoughts?

Thank you for your help.

**Comment by nljones** [comment]
> Maybe you meant that having made those changes, and done a build, the resulting rtrace_dc can be renamed to rtrace_dc_2305.

Yes.

> Do you have any further thoughts?

In daysim.h, change `DAYSIM_MAX_COEFS` from 148 to 2306.

There may be other changes required as well.

**Comment by nljones** [comment]
I've simplified the process for creating rtrace_dc_2305 by adding a DDS flag to the code, which can be set similarly to the DAYSIM flag. I've also updated the documentation on the main page.
