### ISSUE TITLE
isotrop_sky.cal error

### ISSUE THREAD

**Issue by dnix** [MITSustainableDesignLab/Daysim#7]
I am trying to run gen_dc after compiling Daysim on linux (per the readmes), and when I run `gen_dc` I'm hitting the following error/warning:

`/usr/local/bin/rtrace_dc: system - cannot find function file "isotrop_sky.cal": No such file or directory`

I do see a reference at https://github.com/MITSustainableDesignLab/Daysim/blob/master/src/daysim/gen_dc.c#L548... any ideas? Thanks in advance!

**Comment by nljones** [comment]
You can create `isotrop_sky.cal` in a location in your RAYPATH with the following contents:
```
skybright = A1 ;
```
Alternatively, delete the line referring to `isotrop_sky.cal` that you found and change the following line as follows:
```
fprintf( skyFile, "void glow sky\n0\n0\n4  1000 1000 1000  0\n\n" );
```

**Comment by nljones** [comment]
I have removed the reference to `isotrop_sky.cal` in the latest commit 76caeb9f682ecb81de08f68db1cff70590b78842.

**Comment by dnix** [comment]
Fantastic! That did the trick. Thanks again, really appreciate it
